basePath: /api/v2
definitions:
  dto.CreateBookRequest:
    properties:
      author:
        minLength: 1
        type: string
      title:
        minLength: 1
        type: string
    required:
    - author
    - title
    type: object
  dto.UpdateBookRequest:
    properties:
      author:
        minLength: 1
        type: string
      title:
        minLength: 1
        type: string
    required:
    - author
    - title
    type: object
host: localhost:8080
info:
  contact: {}
  description: เวอร์ชันสองของ Book API (อาจเปลี่ยนรูปแบบ response บางส่วน)
  title: Book API (v2)
  version: "2.0"
paths:
  /books:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: List books (v2)
      tags:
      - books-v2
    post:
      consumes:
      - application/json
      parameters:
      - description: payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateBookRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create book (v2)
      tags:
      - books-v2
  /books/{id}:
    delete:
      parameters:
      - description: book id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete book (soft delete) (v2)
      tags:
      - books-v2
    get:
      parameters:
      - description: book id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get book by id (v2)
      tags:
      - books-v2
    put:
      consumes:
      - application/json
      parameters:
      - description: book id
        in: path
        name: id
        required: true
        type: integer
      - description: payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update book (v2)
      tags:
      - books-v2
schemes:
- http
swagger: "2.0"
